config/routes.rb
AcademiaRails::Application.routes.draw do

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  get 'user' => "registrations#new", as: :new


  # authenticated :user do
  #   root :to => 'home#index'
  # end

  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  resources :tags

   scope module: 'course' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    post 'pages/gracias'
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'welcome' => 'pages#welcome', as: :welcome
  end

  root :to => "course/pages#welcome"


  devise_for :authors, :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :posts
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user_or_author!

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<h1 id="secciones_tags">Secciónes</h1>

<div class="container">
  <% @tags.each_slice(1) do |tags| %>
    <div class="row">
      <% tags.each do |tag| %>
        <div class="col-md-8" id="tagSection">
          <%= link_to tag.name, tag_path(tag) %>


          <% if author_signed_in? %>
          <%= link_to "delete", tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"} %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="footer">
  <h1></h1>
</div>

app/views/tags/show.html.erb
<h1 id="secciones_tags"><%= @tag.name %> lecciones</h1>

<div class="container">
  <div class="row">
  <% @tag.posts.each do |post| %>
    <div class="col-md-8" id="tagSection">
      <%= link_to post.title, post_path(post) %>
      <p class="card-text-lesson"><%= truncate(post.description, length: 130) %></p>
    </div>
  <% end %>
  </div>
</div>