config/routes.rb
AcademiaRails::Application.routes.draw do

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  get 'user' => "registrations#new", as: :new


  # authenticated :user do
  #   root :to => 'home#index'
  # end

  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  resources :tags

   scope module: 'course' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    post 'pages/gracias'
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'welcome' => 'pages#welcome', as: :welcome
  end

  root :to => "course/pages#welcome"


  devise_for :authors, :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :posts
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable

  has_many :taggings
  has_many :tags, through: :taggings

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  POR_PAGINA = 5

  scope :most_recent, -> {order(published_at: :desc)}
  scope :published, -> {where(published: true)}
  scope :recent_paginated, -> (page) {most_recent.paginate(page: page, per_page: POR_PAGINA)}
  scope :with_tag, -> (tag) {tagged_with(tag) if tag.present? }

  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Published #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not pub yet."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end

end

app/controllers/course/posts_controller.rb
module Course
  class PostsController < CourseController
    before_action :authenticate_user!
    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def post_params
    params.require(:post).permit(:title, :body, :tag_list)
  end
end

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">

      <div class="card">
        <div class="card-block">
          <% if @post.new_record? %>
            <h4 class="card-title"> New Post</h4>
          <% else %>
            <h4 class="card-title">
              <b>Edit</b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
             <div class="field">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
             <div class="field">
              <%= f.label :banner_image_url %>
              <%= f.text_field :banner_image_url, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tags' %>
              <%= f.text_area :tag_list, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
              <div class="actions">
                <%= f.submit "Save lesson", class: 'btn btn-success btn-lg btn-block'%>
              </div>
          </li>
        </ul>
      </div>
      <% if @post.persisted? %>
        <%= link_to 'Show', @post %> |
      <% end %>
      <%= link_to 'Back', authors_posts_path %>
    </div>

    <div class="col-md-8">
      <div class="field">
        <%= f.text_area :body %>
      </div>
    </div>
  </div>
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, authors_post_path(post) %></td>
  <td></td>
  <% if post.published? %>
    <td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
  <td><%= link_to 'Publish',  publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to 'Editar',  edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remover',  authors_post_path(post), method: :delete, data:{ confirm: 'Estas seguro?'}, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, "active") %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, "All Posts") %>
<% provide(:author, "active") %>

<div class="row">
  <div>
    <%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <br>
  <table class="table table-striped">
    <tr>
      <th colspan="5">Titulo</th>
    </tr>
    <%= render @posts %>
  </table>

</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, "active") %>

<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, "active") %>

<div>
  <%= link_to 'Editar',  edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remover',  authors_post_path(@post), method: :delete, data:{ confirm: 'Estas seguro?'}, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p> <%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>
  </div>
</div>