config/routes.rb
AcademiaRails::Application.routes.draw do

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  get 'user' => "registrations#new", as: :new


  # authenticated :user do
  #   root :to => 'home#index'
  # end

  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  resources :tags

   scope module: 'course' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    post 'pages/gracias'
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'welcome' => 'pages#welcome', as: :welcome
  end

  root :to => "course/pages#welcome"


  devise_for :authors, :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :posts
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-l">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Secciónes', tags_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if author_signed_in? %>
          <li class="list-group-item">
            <%= link_to 'mis posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <a class="navbar-brand" href='/welcome'>
      Academia<span class="light">Rails</span>
    </a>
    <!-- <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
&#9776;
</button> -->
<ul class="nav navbar-nav pull-sm-right hidden-xs-down">
  <li class="nav-item">
    <%= link_to 'Secciónes', tags_path, class: "nav-link #{yield(:blog_active)}" %>
  </li>
  <li class="nav-item">
    <%= link_to "About", about_path, class: "nav-link #{yield(:about_active)}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Contact',contact_path, class: "nav-link #{yield(:contact_active)}" %>
  </li>
  <% if author_signed_in? %>
    <li class="nav-item">
      <%= link_to 'mis posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
    </li>
  <% elsif user_signed_in? %>
    <li class="list-group-item">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  <% else %>
          <li class="list-group-item">
            <%= link_to 'Login', new_user_session_path %>
          </li>
<!--           <li class="list-group-item">
            <%= link_to 'Sign Up', new_user_registration_path(:plan => 'platinum'), :class => 'btn btn-primary' %>
          </li> -->
          <!-- remove sign up during beta -->
  <% end %>
</ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:page_title)%> | AcademiaRails</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Stripe Membership Saas" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
   <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
    <!-- <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </div> -->
  </body>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | AcademiaRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cloud.tinymce.com/stable/tinymce.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Fugaz+One|Montserrat|Pacifico|" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/course.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:page_title)%>AcademiaRails</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Stripe Membership Saas" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
   <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>

  </body>
</html>