config/routes.rb
AcademiaRails::Application.routes.draw do

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  get 'user' => "registrations#new", as: :new


  # authenticated :user do
  #   root :to => 'home#index'
  # end

  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  resources :tags

   scope module: 'course' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    post 'pages/gracias'
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'welcome' => 'pages#welcome', as: :welcome
  end

  root :to => "course/pages#welcome"


  devise_for :authors, :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable

  has_many :taggings
  has_many :tags, through: :taggings

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  POR_PAGINA = 5

  scope :most_recent, -> {order(published_at: :desc)}
  scope :published, -> {where(published: true)}
  scope :recent_paginated, -> (page) {most_recent.paginate(page: page, per_page: POR_PAGINA)}
  scope :with_tag, -> (tag) {tagged_with(tag) if tag.present? }

  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Published #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not pub yet."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end

end

app/controllers/course/pages_controller.rb
module Course
  class PagesController < CourseController

    def about
    end

    def contact
    end

    def gracias
      @name = params[:name]
      @email = params[:email]
      @message = params[:message]
      ActionMailer::Base.mail(:from => @email,
          :to => 'academiarails@gmail.com',
          :subject => "A new contact form message from #{@name}",
          :body => @message).deliver_now
    end


  end
end

app/controllers/course/posts_controller.rb
module Course
  class PostsController < CourseController
    before_action :authenticate_user!
    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end

  end

end

app/controllers/course_controller.rb
class CourseController < ApplicationController
end


# class CourseController < ActionController::Base
  # protect_from_forgery

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_path, :alert => exception.message
  # end

  # def after_sign_in_path_for(resource)
  #   case current_user.roles.first.name
  #     when 'admin'
  #       users_path
  #     when 'silver'
  #       content_silver_path
  #     when 'gold'
  #       content_gold_path
  #     when 'platinum'
  #       content_platinum_path
  #     else
  #       root_path
  #   end
  # end

# end

app/helpers/posts_helper.rb
module PostsHelper
  def post_params
    params.require(:post).permit(:title, :body, :tag_list)
  end
end

app/views/course/posts/_post.html.erb
<div class="col-sm-6 col-lg-4">
  <div class="card">
    <%= link_to post do %>
      <div class="card-topper" style="background-image: url(<%= post.banner_image_url %>);"></div>
    <% end %>

    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <p><%= raw post.tags.map{|tag| link_to tag.name, posts_path(tag: tag.name)}.join(', ')%></p>
      <% if author_signed_in? %>
        <p class="published-date"><%= post.display_day_published %></p>
      <% end %>
      <%= link_to post do %>
        <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/course/posts/index.html.erb
<% provide(:page_title, "All Posts") %>
<% provide(:blog_active, "active") %>

<div class="row">

  <%= render @posts %>
</div>

<div class="digg_pagination">
  <%= will_paginate @posts, :container => false %>
</div>

app/views/course/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, "active") %>

<div>
  <% if author_signed_in? %>
    <%= link_to 'Editar',  edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Remover',  authors_post_path(@post), method: :delete, data:{ confirm: 'Estas seguro?'}, class: 'btn btn-sm btn-danger' %>
  <% end %>
</div>

<h1 id="secciones_tags"><%= @post.title %></h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1 col-lg-8 text-xs-center" id="post_body">
    <% if author_signed_in? %>
      <p> <%= @post.display_day_published %></p>
    <% end %>
    <%= @post.body.html_safe %>
  </div>
</div>